spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 1
    port: 6379
    host: localhost
    password: 666666
  logger:
    isdebug: true
management: # 暴露web端点
  endpoints:
    web:
      exposure:
        include: "*"
