server:
  port: 9401
spring:
  profiles:
    active: dev
  application:
    name: micro-oauth2-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848,localhost:8847,localhost:8849
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 1
    port: 6379
    host: localhost
    password: 666666
  logger:
    isdebug: true
management: # 暴露web端点
  endpoints:
    web:
      exposure:
        include: "*"
