spring:
  logger:
    isdebug: true
  profiles:
    active: dev
  cloud:
    gateway:
      routes: #配置路由路径
        - id: oauth2-api-route
          uri: lb://micro-oauth2-api  #转发的地址,写服务名称
          predicates:
            - Path=/api/**            #判断匹配条件,即地址带有/api/**的请求,会转发至lb:micro-oauth2-api
          filters:
            - StripPrefix=1           #去掉Path前缀,参数为1代表去掉/api
        - id: oauth2-auth-route
          uri: lb://micro-oauth2-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 1
    port: 6379
    host: localhost
    password: 666666
  mvc:
    servlet:
      load-on-startup: 1
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/auth/user/register"